# Generated by Django 2.2 on 2019-05-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='provider_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
